# NOTE: update this with your service name
service: kmc

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    KMC_PRODUCT: kmc.product
    KMC_HISTORY: kmc.history

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"

functions:
  addProduct:
    handler: src/add-product.main
    events:
      - http:
          path: products
          method: post
          cors: true

  getProductById:
    handler: src/get-product-by-id.main
    events:
      - http:
          path: products/{id}
          method: get
          cors: true

  getAllProducts:
    handler: src/get-all-products.main
    events:
      - http:
          path: products
          method: get
          cors: true
          request:
              template:
                application/json: >
                  {
                    "isSold": "$input.params('isSold')"
                  }

  updateProduct:
    handler: src/update-product.main
    events:
      - http:
          path: products/{id}
          method: put
          cors: true

  sellProduct:
    handler: src/sell-product.main
    events:
      - http:
          path: products/{id}/sell
          method: post
          cors: true

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
